### ISSUE TITLE
"Automate trade" doesn't do anything.

### ISSUE THREAD

**Issue by Forrce** [We-the-People-civ4col-mod/Mod#442]
Whenever I click the "automate trade" button while any transport unit is selected, nothing happens. I've set up the imports and exports in my colonies properly, but the transport units just go "busy" (with a white light next to the icon as opposed to green), but the units don't move at all. If you force them to pick up materials they will sometimes drop this cargo back into the colony immediately.

[Martim Alfonso de Sousa AD-1563-September_2.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6404448/Martim.Alfonso.de.Sousa.AD-1563-September_2.zip)

**Comment by Nightinggale** [comment]
Confirmed. This is likely a vanilla bug.

What happens is that the wagon train is loaded with ore. It then searches for a trade route where it can start by dropping off ore. Only 3 trade routes are valid and since none of them accepts incoming ore in the colony it should pick up from, none of them are valid. The wagon train then moves to safety in the nearest colony and waits for a traderoute to be valid.

A workaround is to stop the automation, unload the ore manually and then start it again while it's empty. This can be done without updating the mod meaning you can do that right now and continue to play your game.

A proper fix would be to make the wagon train find a traderoute, which carries ore and then only use the second half of it. This does require new coding (not done yet) and updating the mod, hence you won't see that right away.

-----

Unrelated: this savegame crashes the game on load using the development version, but works with the latest release. One more issue to investigate.

**Comment by inaiwae** [comment]
> Unrelated: this savegame crashes the game on load using the development version, but works with the latest release. One more issue to investigate.

sorry to sidetrack from original issue, my current game on huge used to crash when loading from play screen (or what ever to call it) but loaded just fine every time if I went into main menu first and loaded from there ... then around 100 turns in it fixed itself somehow ... maybe it helps you to narrow it down, if it is similar behavior

**Comment by Nightinggale** [comment]
Fixed, though I will keep this open until I figure out the crashing savegame issue.

**Comment by Nightinggale** [comment]
Doesn't look like the crashing savegame is fixable. The game crashes after the savegame has successfully loaded, caches have been set and then it return to code in the exe file. Outside of our code and apparently our code is working flawlessly.

**Comment by Forrce** [comment]
I'm still having the issue after emptying the ore and setting up the imports/exports. I've got two wagon trains as well, one in Sao Paulo and one in Sao Salvador. Both have the same issue even when they're not loaded with cargo. 

Here's a new save where I have the trade routes set up as I like, and the wagon trains are empty, but still the automate transport button still makes the wagon trains retreat and do nothing.

Please help, this has happened in all of my saves so far.

[Martim Alfonso de Sousa AD-1564-January_3.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6410416/Martim.Alfonso.de.Sousa.AD-1564-January_3.zip)

**Comment by Nightinggale** [comment]
I did fix one bug. That doesn't mean there is only one bug at play here though. I will look into this again.

**Comment by Nightinggale** [comment]
I did some testing:

- Works with development version
- Fails with last release

In other words this will be fixed in the next release. If you can't wait, then you can try [compiling the development version](https://github.com/We-the-People-civ4col-mod/Mod/wiki/How-to-play-the-development-version) yourself.

There are two branches you can pick from:

- river_merge: newest version with all the fixes, but can't read your savegames
- Release_Candidate_2_8: not fully updated, but it can read your savegames

Automated wagon trains should work fine in both.

**Comment by Forrce** [comment]
Oh cool, easy as! Thank you so much for all the work you and everyone do for this mod
