### ISSUE TITLE
End of turn crash

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#791]
Hello,
The game crashes with no error on the screen. Using Col 4 WTP mod, v 3.0.1. Is there a place (log folder, specific app launch attribute for DEBUG mode) we can check the actual error ?
[George Washington AD-1593-April.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11157006/George.Washington.AD-1593-April.zip)
As a side note, I've noticed that Spain is spawning ships (Caravela redonda) with some "prepared" settler infinitely. At war with them, I keep capturing/destroying them, but they keep coming every other turn or so, don't know if it's linked to my game crash. 
Thanks a lot for looking into what may cause this issue.

**Comment by MrZorG33** [comment]
use the fix [from here](https://github.com/We-the-People-civ4col-mod/Mod/issues/691) - the problem should be solved.

spain player might have a lot of gold or a very generous king and the AI wants to keep playing.

**Comment by andushow** [comment]
Well, I've applied that fix (before raising my ticket) but it didn't solve my issue. Now, there are 2 choices, eIther:
(1) I didn't apply it correctly (I placed the said DLL in the /Mods/WTP/Assets folder)
(2) Fix doesn't apply to my case.

**Comment by raystuttgart** [comment]
Please wait until we publish Release 4.0 in one or two weeks.
Nobody is working on Release 3.0.1 anymore anyways.

**Comment by devolution79** [comment]
@andushow Did you recompile and check that a new DLL was built and placed in Assets ?

**Comment by raystuttgart** [comment]
@devolution79 
I think he just copied the "fix DLL" for 3.0.1 as it was suggested in the post.
It sounds like he is still playing 3.0.1 release and not with "New Hope".

**Comment by andushow** [comment]
no, I haven't recompiled, I simply placed (copy/paste) the DLL mentioned in the mentioned fix (#691 ).

**Comment by raystuttgart** [comment]
As I said, I understood that. But again, we are short before publishing WTP 4.0.
Nobody is working anymore on release 3.0.1 because it is so outdated by 2 years.

**Comment by andushow** [comment]
> @devolution79 I think he just copied the "fix DLL" for 3.0.1 as it was suggested in the post. It sounds like he is still playing 3.0.1 release and not with "New Hope".

it's true, I'm on 3.0.1 (as mentioned in the initial issue), not that advance to compile 4.0 myself.

**Comment by andushow** [comment]
> As I said, I understood that. But again, we are short before publishing WTP 4.0. Nobody is working anymore on release 3.0.1 because it is outdated by 2 years.

well, then I just have to sit and wait, thanks a lot for your effort guys, really nice !
